name: Release

on: push

jobs:
  build-distributable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean
        run: |
          make build
      - name: Upload assets to an artifact for next steps
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release
          retention-days: 5