name: Release

on: push

env:
  ROOT_DIR: ${{ github.workspace }} 
  DEPS_DIR: ${{ github.workspace }}\deps
  QtBaseDir: ${{ github.workspace }}\deps\QT
  QTDIR32: ${{ github.workspace }}\deps\QT\5.10.1\msvc2017
  QTDIR64: ${{ github.workspace }}\deps\QT\5.10.1\msvc2017_64
  CMAKE_PREFIX_PATH:  ${{ github.workspace }}\deps\QT\5.10.1\msvc2017\lib\cmake\Qt5Widgets
  OBSDepsBasePath: ${{ github.workspace }}\deps\dependencies2019
  DepsBasePath: ${{ github.workspace }}\deps\dependencies2019
  DepsPath64: ${{ github.workspace }}\deps\dependencies2019\win64
  OBSPath: ${{ github.workspace }}\deps\obs-studio
  CPPWSPath: ${{ github.workspace }}\deps\websocketpp
  AsioPath: ${{ github.workspace }}\deps\asio
  buildFolder: ${{ github.workspace }}\deps\release
  build_config: RelWithDebInfo

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-dependencies:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Add msbuild to PATH'
        uses: microsoft/setup-msbuild@v1.1
      - name: Install QT
        shell: cmd
        run: ci\windows\install-qt-win.cmd
      - name: Download OBS deps
        shell: cmd
        run: ci\windows\download-obs-deps.cmd
      - name: Prepare OBS Windows
        shell: cmd
        run: ci\windows\prepare-obs-windows.cmd

  build-obs-32-dependencies:
    runs-on: windows-latest
    needs: [prepare-dependencies]
    steps:
      - uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Build OBS 32
        shell: cmd
        run: |
          echo %OBSPath%
          echo %build_config%
          cd %OBSPath%
          dir
          cd build32
          dir
          


          
