name: Release

on: push

env:
  ROOT_DIR: ${{ env.GITHUB_WORKSPACE }}
  # DEPS_DIR: ${{ env.ROOT_DIR }}\deps
  # QtBaseDir: ${{ env.ROOT_DIR }}\deps\QT

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-dependencies:
    runs-on: window-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install qt
        run: |
          echo "ROOT_DIR=222"
          # echo "DEPS_DIR=${{ env.DEPS_DIR }}"
          # echo "QtBaseDir=${{ env.QtBaseDir }}"
          